"""GUI interface created by Viktor Chmilenko for his beloved wife Marina Sharoyko(Dr. Medizin)"""

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMessageBox


class Ui_MainWindow(object):
    """UI MainWindow"""

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setStyleSheet("background-color: rgb(255, 208, 131);")
        # MainWindow.setIconSize(QtCore.QSize(23, 24))
        # MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(9, 9, 382, 462))
        self.frame.setStyleSheet("background-color: rgb(255, 208, 131);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_Calculate = QtWidgets.QPushButton(self.frame)
        self.pushButton_Calculate.setGeometry(QtCore.QRect(300, 10, 71, 445))
        self.pushButton_Calculate.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.SizeAllCursor))
        self.pushButton_Calculate.setMouseTracking(True)
        self.pushButton_Calculate.setStyleSheet("background-color: rgb(255, 255, 0);\n""font: 12pt \"MS Shell Dlg 2\";")
        self.pushButton_Calculate.setObjectName("pushButton_Calculate")
        self.label_Years_Output = QtWidgets.QLabel(self.frame)
        self.label_Years_Output.setGeometry(QtCore.QRect(10, 412, 275, 41))
        self.label_Years_Output.setStyleSheet(
            "font: 75 18pt \"MS Shell Dlg 2\";\n""background-color: rgb(0, 0, 0);\n""color: rgb(85, 255, 127);")
        self.label_Years_Output.setObjectName("label_Years_Output")
        self.textEdit_Weight_Input = QtWidgets.QTextEdit(self.frame)
        self.textEdit_Weight_Input.setGeometry(QtCore.QRect(80, 10, 204, 42))
        self.textEdit_Weight_Input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit_Weight_Input.setMouseTracking(True)
        self.textEdit_Weight_Input.setAccessibleName("")
        self.textEdit_Weight_Input.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit_Weight_Input.setObjectName("textEdit_Weight_Input")
        self.splitter_2 = QtWidgets.QSplitter(self.frame)
        self.splitter_2.setGeometry(QtCore.QRect(10, 200, 271, 51))
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_Result = QtWidgets.QLabel(self.splitter_2)
        self.label_Result.setStyleSheet(
            "background-color: rgb(129, 129, 129);\n""color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_Result.setObjectName("label_Result")
        self.label_Result_Output = QtWidgets.QLabel(self.splitter_2)
        self.label_Result_Output.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n""color: rgb(255, 255, 255);\n""font: 18pt \"MS Shell Dlg 2\";")
        self.label_Result_Output.setObjectName("label_Result_Output")
        self.splitter = QtWidgets.QSplitter(self.frame)
        self.splitter.setGeometry(QtCore.QRect(10, 120, 271, 41))
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_BMI = QtWidgets.QLabel(self.splitter)
        self.label_BMI.setStyleSheet(
            "background-color: rgb(129, 129, 129);\n""color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_BMI.setObjectName("label_BMI")
        self.lcdNumber_Output = QtWidgets.QLCDNumber(self.splitter)
        self.lcdNumber_Output.setStyleSheet("background-color: rgb(0, 0, 0);\n""color: rgb(255, 255, 127);")
        self.lcdNumber_Output.setObjectName("lcdNumber_Output")
        self.label_Weight = QtWidgets.QLabel(self.frame)
        self.label_Weight.setEnabled(True)
        self.label_Weight.setGeometry(QtCore.QRect(11, 11, 59, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Weight.setFont(font)
        self.label_Weight.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Weight.setObjectName("label_Weight")
        self.label_Height = QtWidgets.QLabel(self.frame)
        self.label_Height.setGeometry(QtCore.QRect(11, 59, 59, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Height.setFont(font)
        self.label_Height.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Height.setObjectName("label_Height")
        self.textEdit_Height_Input = QtWidgets.QTextEdit(self.frame)
        self.textEdit_Height_Input.setGeometry(QtCore.QRect(80, 59, 204, 42))
        self.textEdit_Height_Input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit_Height_Input.setMouseTracking(True)
        self.textEdit_Height_Input.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit_Height_Input.setDocumentTitle("")
        self.textEdit_Height_Input.setObjectName("textEdit_Height_Input")
        self.textEdit_Day_Input = QtWidgets.QTextEdit(self.frame)
        self.textEdit_Day_Input.setGeometry(QtCore.QRect(80, 360, 204, 42))
        self.textEdit_Day_Input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit_Day_Input.setMouseTracking(True)
        self.textEdit_Day_Input.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit_Day_Input.setObjectName("textEdit_Day_Input")
        self.label_Year = QtWidgets.QLabel(self.frame)
        self.label_Year.setEnabled(True)
        self.label_Year.setGeometry(QtCore.QRect(11, 261, 59, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Year.setFont(font)
        self.label_Year.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Year.setObjectName("label_Year")
        self.textEdit_Year_Input = QtWidgets.QTextEdit(self.frame)
        self.textEdit_Year_Input.setGeometry(QtCore.QRect(80, 261, 204, 42))
        self.textEdit_Year_Input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit_Year_Input.setMouseTracking(True)
        self.textEdit_Year_Input.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit_Year_Input.setObjectName("textEdit_Year_Input")
        self.label_Month = QtWidgets.QLabel(self.frame)
        self.label_Month.setGeometry(QtCore.QRect(11, 310, 59, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Month.setFont(font)
        self.label_Month.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Month.setObjectName("label_Month")
        self.textEdit_Monthr_Input = QtWidgets.QTextEdit(self.frame)
        self.textEdit_Monthr_Input.setGeometry(QtCore.QRect(80, 310, 204, 42))
        self.textEdit_Monthr_Input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.textEdit_Monthr_Input.setMouseTracking(True)
        self.textEdit_Monthr_Input.setStyleSheet(
            "background-color: rgb(255, 255, 255);\n""font: 75 18pt \"MS Shell Dlg 2\";")
        self.textEdit_Monthr_Input.setObjectName("textEdit_Monthr_Input")
        self.label_Day = QtWidgets.QLabel(self.frame)
        self.label_Day.setGeometry(QtCore.QRect(11, 360, 59, 42))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Day.setFont(font)
        self.label_Day.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_Day.setObjectName("label_Day")
        # MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        # MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.textEdit_Weight_Input, self.textEdit_Height_Input)
        MainWindow.setTabOrder(self.textEdit_Height_Input, self.textEdit_Year_Input)
        MainWindow.setTabOrder(self.textEdit_Year_Input, self.textEdit_Monthr_Input)
        MainWindow.setTabOrder(self.textEdit_Monthr_Input, self.textEdit_Day_Input)
        MainWindow.setTabOrder(self.textEdit_Day_Input, self.pushButton_Calculate)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BMI + Full Years"))
        self.pushButton_Calculate.setText(_translate("MainWindow", "Calculate"))
        self.label_Years_Output.setText(_translate("MainWindow", "Full Years is: "))
        self.textEdit_Weight_Input.setPlaceholderText(_translate("MainWindow", "type your weight"))
        self.label_Result.setText(_translate("MainWindow", "Result:"))
        self.label_Result_Output.setText(_translate("MainWindow", "Waiting for Data"))
        self.label_BMI.setText(_translate("MainWindow", "BMI:"))
        self.label_Weight.setText(_translate("MainWindow", "Weight"))
        self.label_Height.setText(_translate("MainWindow", "Height"))
        self.textEdit_Height_Input.setPlaceholderText(_translate("MainWindow", "type your height"))
        self.textEdit_Day_Input.setPlaceholderText(_translate("MainWindow", "Day of birth"))
        self.label_Year.setText(_translate("MainWindow", "Year"))
        self.textEdit_Year_Input.setPlaceholderText(_translate("MainWindow", "Year of birth"))
        self.label_Month.setText(_translate("MainWindow", "Month"))
        self.textEdit_Monthr_Input.setPlaceholderText(_translate("MainWindow", "Month of birth"))
        self.label_Day.setText(_translate("MainWindow", "Day"))
